import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await getServerSession(authOptions);
  
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { id } = await params;
  const body = await req.json();
  const { phoneNumbers } = body;

  if (!phoneNumbers || phoneNumbers.length === 0) {
    return NextResponse.json({ error: 'Please provide at least one phone number' }, { status: 400 });
  }

  const meeting = await prisma.meeting.findUnique({
    where: { id },
    include: { 
      user: { select: { name: true } }
    }
  });

  if (!meeting) {
    return NextResponse.json({ error: 'Meeting not found' }, { status: 404 });
  }

  try {
    // Create WhatsApp message
    const message = `
*📋 Meeting: ${meeting.title}*

📅 *Date:* ${new Date(meeting.date).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
⏰ *Time:* ${new Date(meeting.date).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}
👤 *Organizer:* ${meeting.user.name}
${meeting.meetingMode ? `📍 *Mode:* ${meeting.meetingMode}` : ''}
${meeting.meetingLink ? `🔗 *Link:* ${meeting.meetingLink}` : ''}

_Generated by Meeting Management System_
    `.trim();

    // Generate WhatsApp Web URLs
    const whatsappLinks = phoneNumbers.map((phoneNumber: string) => {
      const cleanNumber = phoneNumber.replace(/\D/g, '');
      return {
        phoneNumber: phoneNumber,
        url: `https://wa.me/${cleanNumber}?text=${encodeURIComponent(message)}`
      };
    });

    return NextResponse.json({ 
      message: `WhatsApp links generated for ${phoneNumbers.length} recipient(s)`,
      links: whatsappLinks,
      totalSent: whatsappLinks.length,
      totalFailed: 0,
      successful: whatsappLinks,
      failed: [],
      method: 'whatsapp_web'
    });
  } catch (error: any) {
    console.error('WhatsApp error:', error);
    return NextResponse.json({ 
      error: `Failed to generate WhatsApp links: ${error.message}`
    }, { status: 500 });
  }
}
